"""add last_read_message_id

Revision ID: 22f1993bc899
Revises: 09374b671d13
Create Date: 2026-04-12 13:57:12.378366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f1993bc899'
down_revision: Union[str, Sequence[str], None] = '09374b671d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_participants', sa.Column('last_read_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'last_read_message_id')
    # ### end Alembic commands ###
