"""empty message

Revision ID: 78bf6207a4f2
Revises: f5814fb82577
Create Date: 2026-04-26 20:57:15.772757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78bf6207a4f2'
down_revision: Union[str, Sequence[str], None] = 'f5814fb82577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chat_user', 'chat_participants', ['chat_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_user', 'chat_participants', type_='unique')
    # ### end Alembic commands ###
