"""add crypto identity keys and devices

Revision ID: 7f8990676995
Revises: 78bf6207a4f2
Create Date: 2026-08-01 08:50:45.444006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7f8990676995'
down_revision: Union[str, Sequence[str], None] = '78bf6207a4f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.create_table('user_identity_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.Enum('X25519_ED25519_V1', name='identitykeyalgorithm'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('identity_public_key', sa.Text(), nullable=False),
    sa.Column('signing_public_key', sa.Text(), nullable=False),
    sa.Column('identity_key_signature', sa.Text(), nullable=False),
    sa.Column('signed_prekey_public', sa.Text(), nullable=True),
    sa.Column('signed_prekey_signature', sa.Text(), nullable=True),
    sa.Column('signed_prekey_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('encrypted_private_bundle', sa.Text(), nullable=False),
    sa.Column('kdf_params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['user_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'version', name='uq_identity_key_device_version')
    )
    op.create_index(op.f('ix_user_identity_keys_device_id'), 'user_identity_keys', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_identity_keys_user_id'), 'user_identity_keys', ['user_id'], unique=False)
    op.create_index('uq_identity_key_active_per_device', 'user_identity_keys', ['device_id'], unique=True, postgresql_where=sa.text('is_active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_identity_key_active_per_device', table_name='user_identity_keys', postgresql_where=sa.text('is_active'))
    op.drop_index(op.f('ix_user_identity_keys_user_id'), table_name='user_identity_keys')
    op.drop_index(op.f('ix_user_identity_keys_device_id'), table_name='user_identity_keys')
    op.drop_table('user_identity_keys')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_table('user_devices')
    # ### end Alembic commands ###

    # Autogenerate creates the enum type implicitly with the table but never drops it, so a
    # downgrade/upgrade cycle otherwise fails with "type already exists".
    op.execute("DROP TYPE IF EXISTS identitykeyalgorithm")
