"""add user to chat_participant

Revision ID: 84d9c5e1ac33
Revises: c02fd64a8d3c
Create Date: 2026-04-05 14:30:38.582349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84d9c5e1ac33'
down_revision: Union[str, Sequence[str], None] = 'c02fd64a8d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
