"""add chat key epochs and sender key grants

Revision ID: 9aa1a30c6412
Revises: 7f8990676995
Create Date: 2026-08-01 09:39:29.100383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aa1a30c6412'
down_revision: Union[str, Sequence[str], None] = '7f8990676995'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_crypto_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('crypto_mode', sa.Enum('LEGACY', 'SENDER_KEYS_V1', 'NOT_ENCRYPTED', name='cryptomode'), nullable=False),
    sa.Column('history_visibility', sa.Enum('JOINED', 'SHARED', name='historyvisibility'), nullable=False),
    sa.Column('current_epoch', sa.Integer(), nullable=False),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=False),
    sa.Column('last_rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', name='uq_crypto_settings_chat')
    )
    op.create_index(op.f('ix_chat_crypto_settings_chat_id'), 'chat_crypto_settings', ['chat_id'], unique=False)
    op.create_table('chat_key_epochs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('INITIAL', 'MEMBER_ADDED', 'MEMBER_REMOVED', 'DEVICE_REVOKED', 'PERIODIC', 'MANUAL', name='epochreason'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('member_set_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'epoch', name='uq_chat_epoch')
    )
    op.create_index(op.f('ix_chat_key_epochs_chat_id'), 'chat_key_epochs', ['chat_id'], unique=False)
    op.create_table('sender_key_distributions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('epoch_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('sender_device_id', sa.UUID(), nullable=False),
    sa.Column('sender_key_id', sa.UUID(), nullable=False),
    sa.Column('algorithm', sa.Text(), nullable=False),
    sa.Column('signing_public_key', sa.Text(), nullable=False),
    sa.Column('chain_start_index', sa.Integer(), nullable=False),
    sa.Column('signature', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['epoch_id'], ['chat_key_epochs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_device_id'], ['user_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_id', 'sender_key_id', name='uq_skd_chat_sender_key_id'),
    sa.UniqueConstraint('epoch_id', 'sender_device_id', name='uq_skd_epoch_sender_device')
    )
    op.create_index(op.f('ix_sender_key_distributions_chat_id'), 'sender_key_distributions', ['chat_id'], unique=False)
    op.create_index(op.f('ix_sender_key_distributions_epoch_id'), 'sender_key_distributions', ['epoch_id'], unique=False)
    op.create_index(op.f('ix_sender_key_distributions_sender_user_id'), 'sender_key_distributions', ['sender_user_id'], unique=False)
    op.create_table('sender_key_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('distribution_id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('recipient_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_device_id', sa.UUID(), nullable=False),
    sa.Column('recipient_identity_key_id', sa.UUID(), nullable=False),
    sa.Column('granted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('wrap_algorithm', sa.Text(), nullable=False),
    sa.Column('ephemeral_public_key', sa.Text(), nullable=False),
    sa.Column('wrapped_chain_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distribution_id'], ['sender_key_distributions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_device_id'], ['user_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_identity_key_id'], ['user_identity_keys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('distribution_id', 'recipient_device_id', name='uq_grant_distribution_recipient')
    )
    op.create_index('ix_grant_chat_recipient', 'sender_key_grants', ['chat_id', 'recipient_device_id'], unique=False)
    op.create_index(op.f('ix_sender_key_grants_distribution_id'), 'sender_key_grants', ['distribution_id'], unique=False)
    op.add_column('chat_participants', sa.Column('joined_at_epoch', sa.Integer(), nullable=True))
    op.add_column('chat_participants', sa.Column('history_start_message_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_participants', 'history_start_message_id')
    op.drop_column('chat_participants', 'joined_at_epoch')
    op.drop_index(op.f('ix_sender_key_grants_distribution_id'), table_name='sender_key_grants')
    op.drop_index('ix_grant_chat_recipient', table_name='sender_key_grants')
    op.drop_table('sender_key_grants')
    op.drop_index(op.f('ix_sender_key_distributions_sender_user_id'), table_name='sender_key_distributions')
    op.drop_index(op.f('ix_sender_key_distributions_epoch_id'), table_name='sender_key_distributions')
    op.drop_index(op.f('ix_sender_key_distributions_chat_id'), table_name='sender_key_distributions')
    op.drop_table('sender_key_distributions')
    op.drop_index(op.f('ix_chat_key_epochs_chat_id'), table_name='chat_key_epochs')
    op.drop_table('chat_key_epochs')
    op.drop_index(op.f('ix_chat_crypto_settings_chat_id'), table_name='chat_crypto_settings')
    op.drop_table('chat_crypto_settings')
    # ### end Alembic commands ###

    # Autogenerate creates enum types implicitly with the tables but never drops them, so a
    # downgrade/upgrade cycle would otherwise fail with "type already exists".
    op.execute("DROP TYPE IF EXISTS epochreason")
    op.execute("DROP TYPE IF EXISTS historyvisibility")
    op.execute("DROP TYPE IF EXISTS cryptomode")
