"""empty message

Revision ID: f5814fb82577
Revises: 22f1993bc899
Create Date: 2026-04-20 18:26:46.056721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5814fb82577'
down_revision: Union[str, Sequence[str], None] = '22f1993bc899'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.Text(), nullable=True))
    op.execute("UPDATE users SET full_name=username")
    op.alter_column(
        'users',
        'full_name',
        nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
