/**
 * Cross-implementation conformance check: TypeScript client vs Python backend reference.
 *
 * The two implementations must agree byte-for-byte on every domain-separated blob. When they
 * don't, the symptom in production is an opaque AES-GCM tag failure with no indication of which
 * field drifted — so this compares the intermediate values directly.
 *
 * Usage (from front/):
 *   node --experimental-strip-types scripts/interop-check.mjs "$(<python vectors json>)"
 *
 * The expected vectors are generated by the backend; see npm run interop.
 */
import { webcrypto } from 'node:crypto';

import { sha256 } from '@noble/hashes/sha2.js';

import { safetyNumber, identityBindingMessage } from '../src/app/core/crypto/identity.ts';
import { buildMessageAad } from '../src/app/core/crypto/envelope.ts';
import { buildGrantAad, computeMemberSetHash, distributionSigningPayload } from '../src/app/core/crypto/grants.ts';
import { b64uEncode, concatBytes, DS_CHANNEL_POST, utf8, uuidBytes } from '../src/app/core/crypto/primitives.ts';
import { advanceChain, deriveMessageKey } from '../src/app/core/crypto/ratchet.ts';

if (!globalThis.crypto) {
    globalThis.crypto = webcrypto;
}

const USER = '11111111-1111-1111-1111-111111111111';
const DEV = 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';
const CHAT = '33333333-3333-3333-3333-333333333333';
const SKID = '77777777-7777-7777-7777-777777777777';
const RDEV = '99999999-9999-9999-9999-999999999999';
const POST = '55555555-5555-5555-5555-555555555555';

const ck = Uint8Array.from({ length: 32 }, (_, i) => i);
const k32 = Uint8Array.from({ length: 32 }, (_, i) => 100 + i);
const k32b = Uint8Array.from({ length: 32 }, (_, i) => 200 + i);

const { key: mk, nonce } = deriveMessageKey(ck);

const postPayload = concatBytes(
    DS_CHANNEL_POST,
    uuidBytes(CHAT),
    uuidBytes(USER),
    uuidBytes(POST),
    sha256(utf8('Release 2.0 ships on Friday.'))
);

const actual = {
    message_key: b64uEncode(mk),
    nonce: b64uEncode(nonce),
    next_chain_key: b64uEncode(advanceChain(ck)),
    msg_aad: b64uEncode(buildMessageAad(CHAT, 5, USER, SKID, 42)),
    binding: b64uEncode(identityBindingMessage(USER, DEV, k32)),
    member_set_hash: computeMemberSetHash([DEV, RDEV, CHAT]),
    dist_payload: b64uEncode(distributionSigningPayload(CHAT, 7, SKID, k32, 3)),
    grant_aad: b64uEncode(
        buildGrantAad({
            chatId: CHAT,
            epoch: 3,
            senderKeyId: SKID,
            senderDeviceId: DEV,
            recipientDeviceId: RDEV,
            ephemeralPublic: k32,
        })
    ),
    post_payload: b64uEncode(postPayload),
    safety_number: safetyNumber(k32, k32b),
};

const expected = JSON.parse(process.argv[2]);

let pass = 0;
let fail = 0;

for (const [name, want] of Object.entries(expected)) {
    const got = actual[name];
    if (got === want) {
        console.log(`  PASS  ${name}`);
        pass += 1;
    } else {
        console.log(`  FAIL  ${name}`);
        console.log(`        python: ${want}`);
        console.log(`        client: ${got}`);
        fail += 1;
    }
}

console.log(`\n${pass} matched, ${fail} mismatched`);
process.exit(fail ? 1 : 0);
