import uuid
from datetime import datetime

from sqlalchemy import String, Boolean, DateTime, ForeignKey, func
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.postgres import Base


class UserDevice(Base):
    """One client installation holding its own keypair.

    Multi-device is not shipping yet — every user has exactly one device for now. The dimension
    exists from the start because retrofitting it later would mean re-wrapping every sender-key
    grant in the system, since grants are addressed to a device rather than a user.

    `id` is generated by the *client*, not the server, and persisted locally. It has to be: the
    client signs over the device id to bind its X25519 key to it, so a server-assigned id would
    force a second round trip to sign something the client could not know in advance. A client
    that supplies an id already taken by another user simply gets a primary-key conflict.
    """
    __tablename__ = "user_devices"

    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True)

    user_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True
    )

    display_name: Mapped[str] = mapped_column(String(100), nullable=False, default="default")

    is_active: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    last_seen_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    user = relationship("User")
